on:
  workflow_call:

jobs:
  reuse:
    name: Reuse
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ secrets.TEST }}
          echo ${{ vars.TEST_VAR }}
