on:
  workflow_call:
    inputs:
      message:
        required: false
        type: string
    secrets:
      TEST:
        required: true

jobs:
  reuse:
    name: Reuse
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ secrets.TEST }}
          echo ${{ vars.TEST_VAR }}
          echo ${{ github.repository }}
          echo ${{ github.ref_name }}
          echo ${{ inputs.message }}
          echo ${{ github.actor }}
          echo ${{ github.run_id }}
          echo ${{ github.event_name }}
          echo ${{ toJson(needs) }}
